apiVersion: v1
kind: Secret
metadata:
  name: islamic-app-secrets
  namespace: islamic-app
type: Opaque
data:
  # Base64 encoded values
  # postgresql://islamic_user:islamic_pass123@postgres:5432/islamic_app
  database-url: cG9zdGdyZXNxbDovL2lzbGFtaWNfdXNlcjppc2xhbWljX3Bhc3MxMjNAcG9zdGdyZXM6NTQzMi9pc2xhbWljX2FwcA==
  # islamic_user
  postgres-user: aXNsYW1pY191c2Vy
  # islamic_pass123
  postgres-password: aXNsYW1pY19wYXNzMTIz
  # islamic_app
  postgres-db: aXNsYW1pY19hcHA=
  # your-super-secret-key-change-in-production
  secret-key: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  # your-jwt-secret-key-change-in-production
  jwt-secret-key: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: islamic-app-config
  namespace: islamic-app
data:
  FLASK_ENV: "production"
  CORS_ORIGINS: "http://localhost:3000,http://localhost:8090,http://islamic-app-frontend:3000,http://localhost:32434,http://localhost:30080,http://controlplane:32434"
  REACT_APP_API_URL: "/api"
  NODE_ENV: "production"
---
