apiVersion: apps/v1
kind: Deployment
metadata:
  name: islamic-app-frontend
  namespace: islamic-app
  labels:
    app: islamic-app-frontend
spec:
  replicas: 1  # Reduced from 3 to 1
  selector:
    matchLabels:
      app: islamic-app-frontend
  template:
    metadata:
      labels:
        app: islamic-app-frontend
    spec:
      containers:
      - name: frontend
        image: khaledhawil/islamic-app_frontend:32-a4669a5
        # imagePullPolicy: Never  # For local development
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: islamic-app-config
              key: REACT_APP_API_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: islamic-app-config
              key: NODE_ENV
        ports:
        - containerPort: 3000
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        # resources:
        #   requests:
        #     memory: "128Mi"  # Reduced from 256Mi
        #     cpu: "100m"      # Reduced from 250m
        #   limits:
        #     memory: "256Mi"  # Reduced from 512Mi
        #     cpu: "200m"      # Reduced from 500m

---
apiVersion: v1
kind: Service
metadata:
  name: islamic-app-frontend
  namespace: islamic-app
  labels:
    app: islamic-app-frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: islamic-app-frontend
---
