# Static inventory for local testing
all:
  children:
    jenkins:
      hosts:
        jenkins-server:
          ansible_host: "{{ terraform_output.jenkins_public_ip | default('localhost') }}"
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/islamic-app-key.pem
    
    eks_nodes:
      hosts:
        # EKS nodes are managed by AWS, but we can configure them if needed
      vars:
        kubernetes_cluster_name: "{{ terraform_output.eks_cluster_name | default('islamic-app-production-eks') }}"
    
  vars:
    # Global variables
    aws_region: us-west-2
    environment: production
    project_name: Islamic-App
    
    # Database configuration
    database_endpoint: "{{ terraform_output.rds_endpoint | default('localhost') }}"
    database_name: islamic_app
    database_username: islamic_user
    
    # Application configuration
    app_name: islamic-app
    app_port: 5000
    frontend_port: 3000
    
    # Docker registry
    ecr_registry: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
