---
# Main playbook for Islamic App infrastructure configuration
- name: Configure Jenkins Server
  hosts: jenkins
  become: true
  roles:
    - common
    - docker
    - jenkins
    - trivy
    - sonarqube
    - cloudwatch

- name: Deploy ArgoCD on EKS
  hosts: localhost
  gather_facts: false
  roles:
    - argocd
  vars:
    eks_cluster_name: "{{ hostvars['eks-cluster']['cluster_name'] }}"
    aws_region: "{{ hostvars['eks-cluster']['aws_region'] }}"
