apiVersion: v1
kind: Secret
metadata:
  name: {{ include "islamic-app.fullname" . }}-secrets
  namespace: {{ include "islamic-app.namespace" . }}
  labels:
    {{- include "islamic-app.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "islamic-app.databaseUrl" . }}
  postgres-user: {{ .Values.postgresql.auth.postgresUser | b64enc }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}
  postgres-db: {{ .Values.postgresql.auth.postgresDatabase | b64enc }}
  secret-key: {{ .Values.app.secrets.secretKey | b64enc }}
  jwt-secret-key: {{ .Values.app.secrets.jwtSecretKey | b64enc }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "islamic-app.fullname" . }}-config
  namespace: {{ include "islamic-app.namespace" . }}
  labels:
    {{- include "islamic-app.labels" . | nindent 4 }}
data:
  FLASK_ENV: {{ .Values.app.config.flaskEnv | quote }}
  CORS_ORIGINS: {{ .Values.app.config.corsOrigins | quote }}
  REACT_APP_API_URL: {{ .Values.app.config.reactAppApiUrl | quote }}
  NODE_ENV: {{ .Values.app.config.nodeEnv | quote }}
